mod core;
mod git;
pub mod http;
mod local;
pub use core::AddrAccessor;
pub use git::GitAccessor;
pub use http::HttpAccessor;
pub use local::LocalAccessor;
pub use local::rename_path;
mod universal;
pub use universal::UniversalAccessor;
pub use universal::UniversalConfig;