name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  release:
    name: Publish and Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
      - name: Verify tag matches Cargo.toml version
        shell: bash
        run: |
          TAG="${GITHUB_REF_NAME}"
          TAG_VER="${TAG#v}"
          CRATE_VER=$(sed -n 's/^version\s*=\s*\"\(.*\)\"/\1/p' Cargo.toml | head -n1)
          echo "Tag: ${TAG_VER} | Crate: ${CRATE_VER}"
          test "${TAG_VER}" = "${CRATE_VER}"
      - name: Cargo package (dry run)
        run: cargo package
      - name: Publish to crates.io
        env:
          CARGO_TERM_COLOR: always
        run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
