name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  publish-crate:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    needs: create-release
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
      - name: Verify tag matches Cargo.toml version
        run: |
          TAG_NAME="${GITHUB_REF##*/}"
          TAG_VER="${TAG_NAME#v}"
          CRATE_VER=$(sed -n 's/^version\s*=\s*\"\(.*\)\"/\1/p' Cargo.toml | head -n1)
          echo "Tag: ${TAG_VER} | Crate: ${CRATE_VER}"
          test "${TAG_VER}" = "${CRATE_VER}"
      - name: Cargo package (dry run)
        run: cargo package
      - name: Publish
        env:
          CARGO_TERM_COLOR: always
        run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}
